name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Test with pytest
      run: |
        cp apps/nametag/.envtemplate .env
        pip install pytest
        PYTHONPATH=. pytest
